 #+STARTUP: overview
 #+TAGS: OFFICE(o) COMPUTER(c) HOME(h) PROJECT(p) READING(r) DVD(d) 
 #+STARTUP: hidestars
* Fish Bowl
** 
* Moms Ideas
Are your servers treating your customers the way they should be?
Were you greeted in a timely manner?
Did you get your food in a reasonable amount of time?
http://media.photobucket.com/image/store cashier/lucad822/cashier_grocery_store.jpg?o=0


http://media.photobucket.com/image/texting/thrivechurch/texting.png?o=59
We would like to know what you thought of your visit today
Please text your answers to a few short questions and receive a coupon code in a text to use on your next visit

Here are a few ideas.  Still thinking
what's the user name and password for the phone no. site?
**  Can you trust all of your employees to treat all of the customers they way they should be treated even when your not there?

* Stuff for Shaun <2011-10-21 Fri>
* Site
** g
** Home
** Customers
*** TODO Landing Page
**** 
* Letters
** Burgio Family Assholes
Dear Burgio Family, 
This is Mr. Shaun M Hannah, April's boyfriend of 3
years. But I'm not writing this because I'm her boyfriend, I writing

because I can't just sit back and watch this happen. It isn't right. 
Now don't take this the wrong way, I know you guys are smart; and your
plan on getting this car back looks like it is working great. Mr. Father
Burgio must be proud of such a well executed plan. 

So now that things have been set in motion I just have to ask what
exactly is your motivation in this? You say it is about Tom buying a
house, but that just doesn't add up to me. How will this effect him
getting approved? The car is upside down in the loan, so you will
loose your ass if you try to sell it. The money you will loose in the
deal will take away from your down payment, not to mention the fact
when the car does get repo'd it will have a huge negative impact on his Tom and
April's credit. Also keep in mind that the payment is over due at this
moment, something that should be keeping such credit consious people
like yourselves up all night. But somehow that doesn't seem to bother
any of you. So I have to ask again, what is your motivation in all of
this. If what you were saying is true, and it is just about Tom
getting a house, then why are you sacrificing his credit in doing all
this? If you think about it, it really doesn't make much sense. 

So have you thought about it? Somehow I think you must have overlooked
some of these issues. Or maybe there are other motivatons. I don't
know, and frankly I don't really care. What I do care about is the
fact that April is sitting here on the verge of a nervous breakdown
because of this. The sick part of this whole situation has nothing to
do with April, or the car; it has more to do with fact there exists
people in this world who take pride in other peoples struggles. People
who would go out of their way to inflict pain and distress on someone
elses life. 

I've known Tom long enough to see that he is one of those kinds of
people. You can try to deny that all you want, and you can say he is a
great man; but his actions have spoke volumes about his true
charactor. I truly beleive that this car situation is nothing more
than an outlet for his own need to bring others down. This is a common
trait amoung people who lack confidence or self esteem. In elementrary
school you would call him a bully; but we are all adults here right? Tom
puts on a good show in his life. He is great at pretending he is a nice
guy, he actually had me fooled too for a couple of years. But this act
that he puts on does not hide the fact that has no respect for the
women in his life. If he did he would not physically, mentally, and
financially abuse them the way he does. He has done all three to
April, and countless others I'm sure. I've seen April in tears
recalling how he slammed her head into a tile floor by her pony tail,
and I've seen her in tears after he tresspassed into her home to
take the plates off her car. He has done countless other things that I
won't even go into detail about.

When you put all the pieces together I think his true motivation is
pretty obvious here. It is a pattern that has been happening over and
over again. And it won't stop after he takes possession of the
car. At some point in his life he'll have to take responsibility for
his actions. If he continues on this path that time might come sooner
than later. God forbid this ever goes to trial because then all of
darkest secrets might be exposed. But in the meantime I'd advise him
to man up and take some responsability for the deecisions he has
made. Nobody made him sign the aggreement, or put his name on the
loan. He made that choice himself. He gave her his word, but in my
experiance, that isn't worth very much. 

I've told April that success is the best form of revenge, it is also the
best way to buy a house...

Shaun
